//
// Created by Radio on 16/06/2024.
//

#ifndef BEMANIMETADATAPARSER_SDVXDIFFICULTY_HPP
#define BEMANIMETADATAPARSER_SDVXDIFFICULTY_HPP

#ifdef INFINITE
#define INFINITE_COPY INFINITE
#undef INFINITE
#endif

#include <cstdint>

enum class SDVXDifficulty : std::uint8_t {
    NOVICE = 0,
    ADVANCED = 1,
    EXHAUST = 2,
    INFINITE = 3,
    MAXIMUM = 4,
};

#ifdef INFINITE_COPY
#define INFINITE INFINITE_COPY
#undef INFINITE_COPY
#endif

#endif //BEMANIMETADATAPARSER_SDVXDIFFICULTY_HPP
