//
// Created by Radio on 07/06/2024.
//

#ifndef BEMANIMETADATAPARSER_CHARTMANAGER_HPP
#define BEMANIMETADATAPARSER_CHARTMANAGER_HPP


class ChartManager {

};


#endif //BEMANIMETADATAPARSER_CHARTMANAGER_HPP
