services:
  build-linux:
    build:
      context: .
      dockerfile: linux.Dockerfile
    volumes:
      - .:/app
      - build:/build
    tty: true
    entrypoint: /bin/bash
    command: -c "cmake -B /build -S . -DCMAKE_BUILD_TYPE=Release && cd /build && make && cp BemaniMetadataParser /app/BemaniMetadataParser-linux && cp DDL.sql /app/DDL.sql"

volumes:
  build: