services:
  build-linux:
    build:
      context: .
      dockerfile: linux.Dockerfile
    volumes:
      - .:/app
    tty: true
    entrypoint: /bin/bash
    command: -c "cmake -B /build -S . -DCMAKE_BUILD_TYPE=Release && cd /build && make && cp BemaniMetadataParser /app/BemaniMetadataParser-linux"