name: Build

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run CMake
        run: cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: BemaniMetadataParser-windows
          path: build/BemaniMetadataParser.exe

  build_linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up build essentials
        run: sudo apt-get install -y build-essential

      - name: Run CMake
        run: cmake -B build -S . -D CMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cd ./build && make

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: BemaniMetadataParser-linux
          path: build/BemaniMetadataParser