name: build

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run CMake
        run: cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: List all files in build directory
        run: ls -R build

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: my-executable
          path: build/Release/BemaniMetadataParser.exe